targetScope = 'managementGroup'

metadata name = 'infra_azure_sre_role'
metadata description = 'Instrastructure Support Azure SRE Role with monitoring and recovery permissions.'

@sys.description('The management group scope to which the role can be assigned.  This management group ID will be used for the assignableScopes property in the role definition.')
param parAssignableScopeManagementGroupId string

var varRole = {
  name: '[${managementGroup().name}] Infrastructure Support Azure SRE Role'
  description: 'Instrastructure Support Azure SRE Role with monitoring and recovery permissions.'
}

resource resRoleDefinition 'Microsoft.Authorization/roleDefinitions@2022-04-01' = {
  name: guid(varRole.name, parAssignableScopeManagementGroupId)
  properties: {
    roleName: varRole.name
    description: varRole.description
    type: 'CustomRole'
   permissions: [
      {
        actions: [
          '*/read'
          'Microsoft.AlertsManagement/actionRules/*'
          'Microsoft.AlertsManagement/alerts/*'
          'Microsoft.AlertsManagement/alertsSummary/*'
          'Microsoft.AlertsManagement/migrateFromSmartDetection/*'
          'Microsoft.AlertsManagement/smartDetectorAlertRules/*'
          'Microsoft.AlertsManagement/smartGroups/*'
          'Microsoft.Authorization/*/read'
          'Microsoft.Automation/automationAccounts/hybridRunbookWorkerGroups/read'
          'Microsoft.Automation/automationAccounts/jobs/output/read'
          'Microsoft.Automation/automationAccounts/jobs/read'
          'Microsoft.Automation/automationAccounts/jobs/resume/action'
          'Microsoft.Automation/automationAccounts/jobs/stop/action'
          'Microsoft.Automation/automationAccounts/jobs/streams/read'
          'Microsoft.Automation/automationAccounts/jobs/suspend/action'
          'Microsoft.Automation/automationAccounts/jobs/write'
          'Microsoft.Compute/virtualMachines/restart/action'
          'Microsoft.Compute/virtualMachines/start/action'
          'Microsoft.Dashboard/checkNameAvailability/action'
          'Microsoft.Dashboard/grafana/delete'
          'Microsoft.Dashboard/grafana/read'
          'Microsoft.Dashboard/grafana/write'
          'Microsoft.Dashboard/locations/operationStatuses/read'
          'Microsoft.Dashboard/locations/operationStatuses/write'
          'Microsoft.Dashboard/locations/read'
          'Microsoft.Dashboard/operations/read'
          'Microsoft.Dashboard/register/action'
          'Microsoft.Dashboard/registeredSubscriptions/read'
          'Microsoft.Dashboard/unregister/action'
          'Microsoft.Insights/actiongroups/*'
          'Microsoft.Insights/activityLogAlerts/*'
          'Microsoft.Insights/AlertRules/*'
          'Microsoft.Insights/components/*'
          'Microsoft.Insights/dataCollectionEndpoints/*'
          'Microsoft.Insights/dataCollectionRuleAssociations/*'
          'Microsoft.Insights/dataCollectionRules/*'
          'Microsoft.Insights/DiagnosticSettings/*'
          'Microsoft.Insights/eventtypes/*'
          'Microsoft.Insights/LogDefinitions/*'
          'Microsoft.Insights/metricalerts/*'
          'Microsoft.Insights/MetricDefinitions/*'
          'Microsoft.Insights/Metrics/*'
          'Microsoft.Insights/privateLinkScopeOperationStatuses/*'
          'Microsoft.Insights/privateLinkScopes/*'
          'Microsoft.Insights/Register/Action'
          'Microsoft.Insights/scheduledqueryrules/*'
          'Microsoft.Insights/webtests/*'
          'Microsoft.Insights/workbooks/*'
          'Microsoft.Insights/workbooktemplates/*'
          'Microsoft.Network/virtualNetworks/read'
          'Microsoft.OperationalInsights/workspaces/analytics/query/action'
          'Microsoft.OperationalInsights/workspaces/intelligencepacks/*'
          'Microsoft.OperationalInsights/workspaces/savedSearches/*'
          'Microsoft.OperationalInsights/workspaces/search/action'
          'Microsoft.OperationalInsights/workspaces/sharedKeys/action'
          'Microsoft.OperationalInsights/workspaces/storageinsightconfigs/*'
          'Microsoft.OperationalInsights/workspaces/write'
          'Microsoft.RecoveryServices/locations/allocatedStamp/read'
          'Microsoft.RecoveryServices/locations/backupPreValidateProtection/action'
          'Microsoft.RecoveryServices/locations/backupStatus/action'
          'Microsoft.RecoveryServices/locations/backupValidateFeatures/action'
          'Microsoft.RecoveryServices/locations/operationStatus/read'
          'Microsoft.RecoveryServices/operations/read'
          'Microsoft.RecoveryServices/Vaults/backupEngines/read'
          'Microsoft.RecoveryServices/Vaults/backupFabrics/backupProtectionIntent/read'
          'Microsoft.RecoveryServices/Vaults/backupFabrics/backupProtectionIntent/write'
          'Microsoft.RecoveryServices/Vaults/backupFabrics/operationResults/read'
          'Microsoft.RecoveryServices/Vaults/backupFabrics/protectableContainers/read'
          'Microsoft.RecoveryServices/Vaults/backupFabrics/protectionContainers/inquire/action'
          'Microsoft.RecoveryServices/Vaults/backupFabrics/protectionContainers/items/read'
          'Microsoft.RecoveryServices/Vaults/backupFabrics/protectionContainers/operationResults/read'
          'Microsoft.RecoveryServices/Vaults/backupFabrics/protectionContainers/protectedItems/backup/action'
          'Microsoft.RecoveryServices/Vaults/backupFabrics/protectionContainers/protectedItems/operationResults/read'
          'Microsoft.RecoveryServices/Vaults/backupFabrics/protectionContainers/protectedItems/operationsStatus/read'
          'Microsoft.RecoveryServices/Vaults/backupFabrics/protectionContainers/protectedItems/read'
          'Microsoft.RecoveryServices/Vaults/backupFabrics/protectionContainers/protectedItems/recoveryPoints/provisionInstantItemRecovery/action'
          'Microsoft.RecoveryServices/Vaults/backupFabrics/protectionContainers/protectedItems/recoveryPoints/read'
          'Microsoft.RecoveryServices/Vaults/backupFabrics/protectionContainers/protectedItems/recoveryPoints/restore/action'
          'Microsoft.RecoveryServices/Vaults/backupFabrics/protectionContainers/protectedItems/recoveryPoints/revokeInstantItemRecovery/action'
          'Microsoft.RecoveryServices/Vaults/backupFabrics/protectionContainers/protectedItems/write'
          'Microsoft.RecoveryServices/Vaults/backupFabrics/protectionContainers/read'
          'Microsoft.RecoveryServices/Vaults/backupFabrics/protectionContainers/write'
          'Microsoft.RecoveryServices/Vaults/backupFabrics/refreshContainers/action'
          'Microsoft.RecoveryServices/Vaults/backupJobs/*'
          'Microsoft.RecoveryServices/Vaults/backupJobsExport/action'
          'Microsoft.RecoveryServices/Vaults/backupOperationResults/*'
          'Microsoft.RecoveryServices/Vaults/backupOperations/read'
          'Microsoft.RecoveryServices/Vaults/backupPolicies/operationResults/read'
          'Microsoft.RecoveryServices/Vaults/backupPolicies/operations/read'
          'Microsoft.RecoveryServices/Vaults/backupPolicies/read'
          'Microsoft.RecoveryServices/Vaults/backupProtectableItems/*'
          'Microsoft.RecoveryServices/Vaults/backupProtectedItems/read'
          'Microsoft.RecoveryServices/Vaults/backupProtectionContainers/read'
          'Microsoft.RecoveryServices/Vaults/backupProtectionIntents/read'
          'Microsoft.RecoveryServices/Vaults/backupstorageconfig/*'
          'Microsoft.RecoveryServices/Vaults/backupUsageSummaries/read'
          'Microsoft.RecoveryServices/Vaults/backupValidateOperation/action'
          'Microsoft.RecoveryServices/Vaults/certificates/write'
          'Microsoft.RecoveryServices/Vaults/extendedInformation/read'
          'Microsoft.RecoveryServices/Vaults/extendedInformation/write'
          'Microsoft.RecoveryServices/Vaults/monitoringAlerts/read'
          'Microsoft.RecoveryServices/Vaults/monitoringAlerts/write'
          'Microsoft.RecoveryServices/Vaults/monitoringConfigurations/*'
          'Microsoft.RecoveryServices/Vaults/read'
          'Microsoft.RecoveryServices/Vaults/registeredIdentities/operationResults/read'
          'Microsoft.RecoveryServices/Vaults/registeredIdentities/read'
          'Microsoft.RecoveryServices/Vaults/registeredIdentities/write'
          'Microsoft.RecoveryServices/vaults/replicationAlertSettings/read'
          'Microsoft.RecoveryServices/vaults/replicationEvents/read'
          'Microsoft.RecoveryServices/vaults/replicationFabrics/read'
          'Microsoft.RecoveryServices/vaults/replicationFabrics/replicationNetworks/read'
          'Microsoft.RecoveryServices/vaults/replicationFabrics/replicationNetworks/replicationNetworkMappings/read'
          'Microsoft.RecoveryServices/vaults/replicationFabrics/replicationProtectionContainers/read'
          'Microsoft.RecoveryServices/vaults/replicationFabrics/replicationProtectionContainers/replicationProtectableItems/read'
          'Microsoft.RecoveryServices/vaults/replicationFabrics/replicationProtectionContainers/replicationProtectedItems/read'
          'Microsoft.RecoveryServices/vaults/replicationFabrics/replicationProtectionContainers/replicationProtectedItems/recoveryPoints/read'
          'Microsoft.RecoveryServices/vaults/replicationFabrics/replicationProtectionContainers/replicationProtectionContainerMappings/read'
          'Microsoft.RecoveryServices/vaults/replicationFabrics/replicationRecoveryServicesProviders/read'
          'Microsoft.RecoveryServices/vaults/replicationFabrics/replicationStorageClassifications/read'
          'Microsoft.RecoveryServices/vaults/replicationFabrics/replicationStorageClassifications/replicationStorageClassificationMappings/read'
          'Microsoft.RecoveryServices/vaults/replicationFabrics/replicationvCenters/read'
          'Microsoft.RecoveryServices/vaults/replicationJobs/read'
          'Microsoft.RecoveryServices/vaults/replicationPolicies/read'
          'Microsoft.RecoveryServices/vaults/replicationRecoveryPlans/read'
          'Microsoft.RecoveryServices/Vaults/usages/read'
          'Microsoft.RecoveryServices/Vaults/vaultTokens/read'
          'Microsoft.Resources/deployments/*'
          'Microsoft.Resources/subscriptions/resourceGroups/read'
          'Microsoft.Resources/subscriptions/resourceGroups/resources/read'
          'Microsoft.Resources/subscriptions/resources/read'
          'Microsoft.Resources/tags/*'
          'Microsoft.Storage/storageAccounts/read'
          'Microsoft.Support/*'
        ]
        notActions: [
          'Microsoft.Compute/virtualMachines/*/delete'
          'Microsoft.OperationalInsights/workspaces/sharedKeys/read'
          'Microsoft.Management/managementGroups/*'
          'Microsoft.Compute/disks/beginGetAccess/action'
        ]
        dataActions: [
        ]
        notDataActions: [
        ]
      }
    ]
    assignableScopes: [
      tenantResourceId('Microsoft.Management/managementGroups', parAssignableScopeManagementGroupId)
    ]
  }
}

output outRoleDefinitionId string = resRoleDefinition.id
